name: github-actions
on: [push]
jobs:
  initial-commit-check:
    runs-on: ubuntu-latest
    steps: 
    - run: echo "Running tests..."
    - run: echo "Current Branch - ${{ github.ref }}"
    - run: echo "Current Commit - ${{ github.sha }}" 
    - run: echo "Current Commit Message - ${{ github.event.head_commit.message }}"
    - name: Checkout
      uses: actions/checkout@v4
    - run: echo " ${{ github.repository }} has been cloned"

  running-testcases:
    runs-on: ubuntu-latest
    steps: 
    - name: Running Test Cases
      uses: actions/checkout@v4
    - run: python3 ./tests.py

  building-docker-image:
    runs-on: ubuntu-latest
    steps: 
    - name: Building Docker Image
      uses: actions/checkout@v4
    - run: docker build -t github-actions .
    - run: docker images
    - run: docker run -d -p 5000:5000 github-actions
    - run: docker ps -a
    - run: docker stop $(docker ps -a -q)
    - run: docker rm $(docker ps -a -q)
    - run: docker rmi $(docker images -q)